core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.root, name='root'),
    path('repairs/', include('repairs.urls')),
    path('moto/', include('moto.urls'))
]

repairs/urls.py
from django.urls import path
from . import views


app_name = 'repair'

urlpatterns = [
    path('', views.index, name='index'),
    path('report/', views.report, name='report'),
    path('new/', views.new, name='new'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('add/<int:pk>/', views.add, name='add'),

    path('items/<int:pk>/', views.items_detail, name='items_detail'),
    path('items/new/', views.items_new, name='items_new'),
    path('items/edit/<int:pk>/', views.items_edit, name='items_edit'),
    path('items/delete/<int:pk>/', views.items_delete, name='items_delete'),

    path('categories/', views.categories_index, name='categories_index'),
    path('categories/<int:pk>/', views.categories_detail, name='categories_detail'),
    path('categories/new/', views.categories_new, name='categories_new'),
    path('categories/edit/<int:pk>/', views.categories_edit, name='categories_edit'),
    path('categories/delete/<int:pk>/', views.categories_delete, name='categories_delete'),
]

templates/category/detail.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% block body %}
<div class="row">
    <div class="col-12 col-sm-8 col-md-10">
        <h1>管理 {{category.name}} 項目</h1>
    </div>
    <div class="col-4 col-sm-4 col-md-2 pl-1 float-right">
        <button type="button" class="btn btn-block btn-primary" data-toggle="modal" data-target="#moto-form-modal">
            新增項目
        </button>
    </div>
    {% url 'repair:items_new' as new_url%}
    {% include 'shared/_form_modal.html' with action=new_url form=create_form name='維修單'%}
</div>
<br>
<div class="row">
    <div class="col-12">
        <table class="table table-striped">
                <thead>
                    <tr class="row">
                        <th class="col-2">子項目管理</th>
                        <th class="col">名稱</th>
                        <th class="col">價格</th>
                        <th class="col-2">類別管理</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in page.object_list %}
                    <tr class="row" >
                        <th class="col-2">
                            {% url 'repair:items_detail' object.id as manage_url %}
                            {% bootstrap_button '管理子項目' button_class="btn-primary" href=manage_url%}
                        </th>
                        <td class="col"><h4>{{object.name}}</h4></td>
                        <td class="col"><h4>{{object.price}}</h4></td>
                        <td class="col-2">
                            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#form-modal-{{object.id}}">
                                修改
                            </button>
                            {% url 'repair:items_edit' object.id as edit_url%}
                            {% include 'shared/_meta_form_modal.html' with action=edit_url form=update_form operator='修改' name='類別' id=object.id%}
                            {% url 'repair:items_delete' object.id as delete_url%}
                            {% bootstrap_button '刪除' button_class="btn-danger" href=delete_url%}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
        </table>
    </div>
    <div class="col-12">
        <div class="float-left">
            {% url 'repair:categories_index' as back_url %}
            {% bootstrap_button '回上一頁' button_class="btn-warning" href=back_url%}
        </div>
        <div class="float-right">
            {% bootstrap_pagination page=page extra=request.GET.urlencode %}
        </div>    
    </div>
  </div>
{% endblock %}

templates/category/index.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% block body %}
<div class="row">
    <div class="col-12 col-sm-10 col-md-10">
        <h1>管理維修類別</h1>
    </div>
    <div class="col-4 col-sm-2 col-md-2 pl-1 float-right">
        <button type="button" class="btn btn-block btn-primary" data-toggle="modal" data-target="#moto-form-modal">
            新增維修類別
        </button>
    </div>
    {% url 'repair:categories_new' as new_url%}
    {% include 'shared/_form_modal.html' with action=new_url form=create_form name='維修類別'%}
</div>
<br>
<div class="row">
    <div class="col-12">
        <table class="table table-striped">
                <thead>
                    <tr class="row">
                        <th class="col-2">項目管理</th>
                        <th class="col">名稱</th>
                        <th class="col-2">類別管理</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in page.object_list %}
                    <tr class="row">
                        <th class="col-2">
                            {% url 'repair:categories_detail' object.id as manage_url %}
                            {% bootstrap_button '管理項目' button_class="btn-primary" href=manage_url%}
                        </th>
                        <td class="col-8"><h4>{{object.name}}</h4></td>
                        <td class="col-2">
                            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#form-modal-{{object.id}}">
                                修改
                            </button>
                            {% url 'repair:categories_edit' object.id as edit_url%}
                            {% include 'shared/_meta_form_modal.html' with action=edit_url form=create_form operator='修改' name='類別' id=object.id%}
                            {% url 'repair:categories_delete' object.id as delete_url%}
                            {% bootstrap_button '刪除' button_class="btn-danger" href=delete_url%}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
        </table>
    </div>
    <div class="col-12">
        <div class="float-right">
            {% bootstrap_pagination page=page extra=request.GET.urlencode %}
        </div>    
    </div>
  </div>
{% endblock %}