core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.root, name='root'),
    path('repairs/', include('repairs.urls')),
    path('moto/', include('moto.urls'))
]

repairs/urls.py
from django.urls import path
from . import views


app_name = 'repair'

urlpatterns = [
    path('', views.index, name='index'),
    path('report/', views.report, name='report'),
    path('new/', views.new, name='new'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('add/<int:pk>/', views.add, name='add'),

    path('items/<int:pk>/', views.items_detail, name='items_detail'),
    path('items/new/', views.items_new, name='items_new'),
    path('items/edit/<int:pk>/', views.items_edit, name='items_edit'),
    path('items/delete/<int:pk>/', views.items_delete, name='items_delete'),

    path('categories/', views.categories_index, name='categories_index'),
    path('categories/<int:pk>/', views.categories_detail, name='categories_detail'),
    path('categories/new/', views.categories_new, name='categories_new'),
    path('categories/edit/<int:pk>/', views.categories_edit, name='categories_edit'),
    path('categories/delete/<int:pk>/', views.categories_delete, name='categories_delete'),
]

repairs/models.py
from django.db import models
from django.core.validators import MinValueValidator
from moto.models import Moto
from custom.models import Custom


class Category(models.Model):
    name = models.CharField('類別名稱', max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '維修類別'
        verbose_name_plural = '維修類別'


class Item(models.Model):
    name = models.CharField('項目名稱', max_length=30)
    price = models.IntegerField('價格', validators=[
        MinValueValidator(1)
    ])
    root = models.ForeignKey('self', verbose_name='隸屬於',
                             blank=True, null=True, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name='大類別',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '維修項目'
        verbose_name_plural = '維修項目'


class Recorder(models.Model):
    moto = models.ForeignKey(Moto, on_delete=models.CASCADE)
    custom = models.ForeignKey(Custom, blank=True, null=True, on_delete=models.CASCADE)
    time = models.DateField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    km = models.IntegerField('里程', default=0)

    class Meta:
        verbose_name = '維修單'
        verbose_name_plural = '維修單'

    def __str__(self):
        return '-'.join([self.moto.id, str(self.time)])


class Detail(models.Model):
    recorder = models.ForeignKey(Recorder, verbose_name='紀錄', on_delete=models.CASCADE)
    item = models.ForeignKey(Item, verbose_name='物件', on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField('項目名稱', default=None,
                            blank=True, null=True, max_length=30)
    price = models.IntegerField('價格', default=0,
                                validators=[
                                    MinValueValidator(1)
                                ])
    count = models.IntegerField('數量', default=0)

    def __str__(self):
        return self.name if self.item is None else self.item.name

    class Meta:
        verbose_name = '維修單細項'
        verbose_name_plural = '維修單細項'

repairs/forms.py
from django.forms import Form, ModelForm, formset_factory, fields, inlineformset_factory
from .models import Recorder, Detail, Item, Category
from custom.models import Custom


class CategoryCreateForm(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class RootItemCreateForm(ModelForm):
    class Meta:
        model = Item
        exclude = ['root', ]


class RootItemUpdateForm(ModelForm):
    name = fields.CharField(label="項目名稱", required=False)

    def clean_name(self):
        data = self.cleaned_data['name']
        if data == '':
            return self.instance.name
        return data

    class Meta:
        model = Item
        exclude = ['root', ]


class ItemCreateForm(ModelForm):
    class Meta:
        model = Item
        fields = '__all__'


class ItemUpdateForm(RootItemUpdateForm):
    class Meta:
        model = Item
        fields = '__all__'


class ReportSearchForm(Form):
    year = fields.IntegerField(label="年", required=False)
    month = fields.IntegerField(label="月", required=False)
    day = fields.IntegerField(label="日", required=False)


class CreateRecorderForm(Form):
    id = fields.CharField(label='車牌號碼')


RepairFormSet = inlineformset_factory(
    Recorder, Detail, exclude=['item'], extra=1)

repairs/views.py
from collections import defaultdict
from calendar import monthrange
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages as m

from .forms import (RepairFormSet,
                    CreateRecorderForm,
                    ReportSearchForm,
                    ItemCreateForm,
                    ItemUpdateForm,
                    RootItemCreateForm,
                    RootItemUpdateForm,
                    CategoryCreateForm)
from .models import Recorder, Category, Item, Detail
from .filters import RecorderFilter
from moto.models import Moto
from core.forms import DeleteConfirmForm


@login_required
def index(request):
    _filter = RecorderFilter(
        request.GET or None,
        queryset=Recorder.objects.all()
    )
    paginator = Paginator(_filter.qs.order_by('-id'), 10)
    page = request.GET.get('page')
    create_form = CreateRecorderForm()
    try:
        page = paginator.page(page)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    return render(request,
                  'repair/index.html',
                  {'filter': _filter,
                   'page': page,
                   'create_form': create_form})


@login_required
def new(request):
    if request.method == "POST":
        moto, _ = Moto.objects.get_or_create(pk=request.POST['id'].upper())
        recorder = Recorder.objects.create(moto=moto)
        return redirect('repair:edit', pk=recorder.pk)
    return redirect('repair:index')


@login_required
def edit(request, pk):
    categories = Category.objects.all()
    recorder = Recorder.objects.get(pk=pk)
    _sum = sum(
        [detail.price*detail.count for detail in recorder.detail_set.all()])
    if request.method == "POST":
        km = request.POST.get('km', None)
        if km and km != recorder.km:
            recorder.km = km
            recorder.save()
        formset = RepairFormSet(request.POST, request.FILES, instance=recorder)
        if formset.is_valid():
            formset.save()
        return redirect('repair:edit', pk=pk)
    else:
        formset = RepairFormSet(instance=recorder)
    return render(request, 'repair/edit.html', {
        'formset': formset,
        'object': recorder,
        'categories': categories,
        'select': 1,
        'sum': _sum
    })


@login_required
def delete(request, pk):
    form = DeleteConfirmForm(request.POST or None)
    recorder = get_object_or_404(Recorder, pk=pk)
    objects = []

    for detail in recorder.detail_set.all():
        detail.fields = {
            detail._meta.get_field(f.name).verbose_name.title(): getattr(detail, f.name, None)
            for f in detail._meta.get_fields()
            if f.name in ['name', 'price', 'count']
        }
        objects.append(detail)

    if request.method == "POST":
        if form.is_valid() and form.cleaned_data['check']:
            recorder.delete()
            m.success(request, '刪除成功')
            return redirect('repair:index')

    return render(
        request,
        'shared/delete_confirm.html',
        {
            'form': form,
            'title': '刪除維修單 #{pk}'.format(pk=pk),
            'objects': objects,
        }
    )


@login_required
def add(request, pk):
    _pk = pk
    recorder = get_object_or_404(Recorder, pk=pk)
    if request.method == "POST":
        add_map = defaultdict(dict)
        for key, value in request.POST.items():
            try:
                pk, name = key.split('-')
                add_map[int(pk)].update({name: value})
            except Exception:
                pass

        # Add for recorder
        for item_id, item in add_map.items():
            try:
                if int(item['count']) == 0:
                    continue

                Detail.objects.create(
                    recorder=recorder,
                    item=Item.objects.get(pk=int(item_id)),
                    name=item['name'],
                    price=item['price'],
                    count=item['count']
                )
            except Exception:
                pass

    return redirect('repair:edit', pk=_pk)


@login_required
def report(request):
    now = datetime.now()
    year, month, day = now.year, now.month, now.day
    start_year, start_month, start_day = year, month, day
    end_year, end_month, end_day = year, month, day
    if request.GET.get('year', None) and request.GET['year'] is not None:
        start_year, start_month, start_day = request.GET['year'], 1, 1
        end_year, end_month, end_day = request.GET['year'], 12, 31
    if request.GET.get('month', None) and request.GET['month'] is not None:
        start_month = end_month = request.GET['month']
        start_day = 1
        _, end_day = monthrange(int(start_year), int(request.GET['month']))
    if request.GET.get('day', None) and request.GET['month'] is not None:
        start_day = end_day = request.GET['day']
    time = {
        'time__start': '-'.join([str(data) for data in [start_year, start_month, start_day]]),
        'time__end': '-'.join([str(data) for data in [end_year, end_month, end_day]])
    }
    _filter = RecorderFilter(
        time,
        queryset=Recorder.objects.all()
    )
    search_form = ReportSearchForm(request.GET or None,)
    paginator = Paginator(_filter.qs.order_by('id'), 10)
    page = request.GET.get('page')
    create_form = CreateRecorderForm()
    try:
        page = paginator.page(page)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    _sum = sum([
        detail.price*detail.count
        for recorder in _filter.qs
        for detail in recorder.detail_set.all()
    ])
    return render(request, 'repair/report.html', {
        'filter': _filter,
        'page': page,
        'create_form': create_form,
        'sum': _sum,
        'search': search_form
    })


@login_required
def items_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    if item.root is None:
        qs = item.item_set.all()
        paginator = Paginator(qs.order_by('-id'), 5)
        page = request.GET.get('page')
        initial = {'category': item.category, 'root': item}
        create_form = ItemCreateForm(initial=initial)
        update_form = ItemUpdateForm(initial=initial)
        create_form.fields['root'].queryset = Item.objects.filter(root=None)
        update_form.fields['root'].queryset = Item.objects.filter(root=None)
        try:
            page = paginator.page(page)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
        return render(
            request,
            'item/detail.html',
            {'page': page,
             'create_form': create_form,
             'update_form': update_form,
             'item': item}
        )
    return redirect('repair:items_detail', pk=item.root.pk)


@login_required
def items_new(request):
    form = ItemCreateForm(request.POST or None)
    item = form.save()
    m.success(request, '新增項目 {name} 成功'.format(name=item.name))
    if item.root is None:
        return redirect('repair:categories_detail', pk=item.category.pk)
    return redirect('repair:items_detail', pk=item.root.pk)


@login_required
def items_edit(request, pk):
    item = get_object_or_404(Item, pk=pk)
    form = RootItemUpdateForm(request.POST or None, instance=item)
    item = form.save()
    m.success(request, '修改項目成功')
    if item.root is None:
        return redirect('repair:categories_detail', pk=item.category.pk)
    return redirect('repair:items_detail', pk=item.root.pk)


@login_required
def items_delete(request, pk):
    item = get_object_or_404(Item, pk=pk)
    item.delete()
    m.success(request, '刪除項目 {name} 成功'.format(name=item.name))
    if item.root is None:
        return redirect('repair:categories_detail', pk=item.category.pk)
    return redirect('repair:items_detail', pk=item.root.pk)


@login_required
def categories_index(request):
    qs = Category.objects.all()
    paginator = Paginator(qs.order_by('-id'), 10)
    page = request.GET.get('page')
    create_form = CategoryCreateForm()
    try:
        page = paginator.page(page)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    return render(request, 'category/index.html',
                  {
                      'page': page,
                      'create_form': create_form,
                  })


@login_required
def categories_detail(request, pk):
    category = Category.objects.get(pk=pk)
    qs = Item.objects.filter(
        root=None,
        category=category
    )
    paginator = Paginator(qs.order_by('-id'), 5)
    page = request.GET.get('page')
    create_form = RootItemCreateForm(initial={'category': category})
    update_form = RootItemUpdateForm(initial={'category': category})
    try:
        page = paginator.page(page)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    return render(
        request,
        'category/detail.html',
        {
            'page': page,
            'create_form': create_form,
            'update_form': update_form,
            'category': category
        }
    )


@login_required
def categories_new(request):
    if request.method == "POST":
        form = CategoryCreateForm(request.POST or None)
        if form.is_valid():
            category = form.save()
            m.success(request, '新增類別 "{name}" 成功'.format(name=category.name))
    return redirect('repair:categories_index')


@login_required
def categories_edit(request, pk):

templates/repair/_index.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% load repair %}
{% block body %}
<div class="row">
    <div class="col-12 col-sm-6 col-md-6">
        <h1>{% block title %}{% endblock %}</h1>
    </div>
    <div class="col-4 col-sm-2 col-md-2 pr-1">
        <a href="{{ request.path }}" class="btn btn-block btn-warning">清除篩選</a>
    </div>
    <div class="col-4 col-sm-2 col-md-2 pl-1">
        <button type="button" class="btn btn-block btn-info" data-toggle="modal" data-target="#moto-filter-modal">
            進階搜尋
        </button>
    </div>
    <div class="col-4 col-sm-2 col-md-2 pl-1">
        <button type="button" class="btn btn-block btn-primary" data-toggle="modal" data-target="#moto-form-modal">
            建立維修單
        </button>
    </div>
    {% url 'repair:new' as new_url%}
    {% include 'shared/_form_modal.html' with action=new_url form=create_form name='維修單'%}
    {% if search %}
    {% include 'shared/_filter_modal.html' with form=search %}
    {% else %}
    {% include 'shared/_filter_modal.html' with form=filter.form %}
    {% endif %}
</div>
<br>
<div class="row">

    {% if filter.qs %}
      <div class="col-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">車牌號碼</th>
			<th scope="col">KM</th>
                        <th scope="col">型號</th>
                        <th scope="col">車主號碼</th>
                        <th scope="col">車主姓名</th>
                        <th scope="col">日期</th>
                        <th scope="col"></th>
                        <th scope="col">總計</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in page.object_list %}
                    <tr>            
                        <th scope="row">
                            <form action="{% url 'repair:new' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" id="id" name="id" value="{{object.moto.id}}">
                                {% bootstrap_button "建立維修單" button_type="submit" button_class="btn-primary" %}
                            </form>
                        </th>
                        <td>{{object.moto.id}}</td>
			<td>{{object.km}}</td>
                        <td>{{object.moto.model | default:'-'}}</td>
                        <td>{{object.moto.owner.phone}}</td>
                        <td>{{object.moto.owner.name}}</td>
                        <td>{{object.time}}</td>
                        <td>
                            {% url 'repair:edit' object.id as edit_url%}
                            {% bootstrap_button '修改' button_class="btn-info" href=edit_url%}
                            {% url 'repair:delete' object.id as delete_url%}
                            {% bootstrap_button '刪除' button_class="btn-danger" href=delete_url%}
                        </td>
                        <td>{{object|sum_recorder}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
      </div>
    <div class="col-12">
        <div class="float-right">
            {% bootstrap_pagination page=page extra=request.GET.urlencode %}
        </div>    
    </div>
    {% if sum %}
        <div class="col-12">
            <div class="float-right">
                總計： {{sum}}
            </div>
        </div>
    {% endif %}
    {% else %}
      <div class="col-12">
        <p class="text-center h5">
          找不到，要不到新增？或是試試進階搜尋！
        </p>
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/repair/_item_form.html
<div class="form-group row">
    <label for="name" class="col-form-label">項目</label>
    <div class="col-8">
        <input id="name" name="{{item.id}}-name" class="form-control here" type="text" value={{item.name}}>
    </div>
</div>
<div class="form-group row">
    <label for="price" class="col-form-label">價格</label>
    <div class="col-8">
        <input id="price" name="{{item.id}}-price" class="form-control here" type="number" value={{item.price}}>
    </div>
</div>
<div class="form-group row">
    <label for="count" class="col-form-label">數量</label>
    <div class="col-8">
        <input id="count" name="{{item.id}}-count" class="form-control here" type="number" value=0>
    </div>
</div>

templates/repair/_items.html
{% load bootstrap4 %}
<div class="card">
    <hr>
    <ul class="nav nav-category mb-3" id="category-tab" role="tablist">
        {% for object in objects%}
        <li class="nav-item">
            <a class="nav-link" id="category-contact-tab" data-toggle="pill" href="#category-contact-{{object.pk}}" role="tab" aria-controls="category-contact-{{object.pk}}"
                aria-selected="false">{{object.name}}</a>
        </li>
        {% endfor %}
    </ul>
    <form action="{% url 'repair:add' pk=pk %}" method="POST">
        <div class="tab-content" id="category-tabContent">
            {% for object in objects%}
            <div class="tab-pane fade" id="category-contact-{{object.pk}}" role="tabpanel" aria-labelledby="category-contact-tab">
                <div id="accordion">
                    {% for item in object.item_set.all %} {% if not item.root %}
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <div class="row">
                                <h5 class="col">
                                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapse-{{item.id}}" aria-expanded="true" aria-controls="collapse-{{item.id}}">
                                        <h3>{{item.name}}</h3>
                                    </button>
                                </h5>
                                <div class="col">
                                    <div class="float-right">
                                        {% include 'repair/_item_form.html' with item=item%}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="collapse-{{item.id}}" class="collapse" aria-labelledby="heading-{{item.id}}" data-parent="#accordion">
                            <div class="card-body">
                                {% for sub_item in item.item_set.all %}
                                <div class="row">
                                    <div class="col">
                                        <h5>{{sub_item.name}}</h5>
                                    </div>
                                    <div class="col">
                                        {% include 'repair/_item_form.html' with item=sub_item%}
                                    </div>
                                </div>
                                <hr> {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endif %} {% endfor %}
                </div>

            </div>
            {% endfor %}
        </div>
        {% csrf_token %}
        <hr>
        {% buttons %}
            <button type="submit" class="btn btn-primary float-right my-2 mx-2">
              新增
            </button>
        {% endbuttons %}
    </form>
</div>

templates/repair/edit.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% block body %}
<div class="row">
    <div class="col-12 col-sm-8 col-md-6">
        <div class="row">
            <div class="col">
                <h1>維修單</h1>
            </div>
            <div class="col float-right">
                <h3>{{object.moto.id}}</h3>
                <h3>{{object.time}}</h3>
            </div>
        </div>
    </div>
</div>
<br>
<div class="row">
    <div class="col-12 col-sm-6 col-md-8">
        {% include 'repair/_items.html' with objects=categories pk=object.pk %}
    </div>
    <div class="col-12 col-sm-6 col-md-4 card">
        <hr>
        <form id="save-form" method="post">
	  <div class="form-group row">
	    <label class="col-md-3 col-form-label" for="km">里程數</label>
	    <div class="col-md-9">
	      <input type="number" name="km" value="{{object.km}}" maxlength="30" class="form-control" placeholder="里程數">
	    </div>
	  </div>
          <hr>
          {% bootstrap_formset formset layout='horizontal' %}
          {% csrf_token %}
        <hr>
        <div class="col">
            <p class="float-left">總計:</p>
            <p id="saved_sum" class="float-right">{{sum}}</p>
        </div>
        <div class="col float-right mx-0 px-0 my-2">
        {% buttons %}
            <button type="submit" class="btn btn-info float-right">
              儲存
            </button>
        {% endbuttons %}
        </div>
        </form>
    </div>
</div>
<script>
</script>
{% endblock %}

{% block script %}
$('#category-tab a[href="#category-contact-{{select}}"]').tab('show')



$(function(){
    $('form :input').change(function(e){
        var i;
        var summary = 0;
        for (i = 0; i < {{formset|length}}; i++) {
            // console.log(i);
            price = $("input[name*='-"+i+"-price'").val();
            count = $("input[name*='-"+i+"-count'").val();
            will_not_delete = !$("input[name*='"+i+"-DELETE'").prop("checked");
            add = price*count*will_not_delete;
            // console.log("price", price);
            // console.log("count", count);
            // console.log("will_not_delete", will_not_delete);
            // console.log("add", add);
            summary += add;
        }
        $("#saved_sum").text(summary);
    });
 });
{% endblock %}

templates/repair/index.html
{% extends 'repair/_index.html' %}
{% load bootstrap4 %}
{% block title %}維修清單{% endblock %}

templates/repair/report.html
{% extends 'repair/_index.html' %}
{% load bootstrap4 %}
{% block title %}維修報表{% endblock %}