core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.root, name='root'),
    path('repairs/', include('repairs.urls')),
    path('moto/', include('moto.urls'))
]

repairs/urls.py
from django.urls import path
from . import views


app_name = 'repair'

urlpatterns = [
    path('', views.index, name='index'),
    path('report/', views.report, name='report'),
    path('new/', views.new, name='new'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('add/<int:pk>/', views.add, name='add'),

    path('items/<int:pk>/', views.items_detail, name='items_detail'),
    path('items/new/', views.items_new, name='items_new'),
    path('items/edit/<int:pk>/', views.items_edit, name='items_edit'),
    path('items/delete/<int:pk>/', views.items_delete, name='items_delete'),

    path('categories/', views.categories_index, name='categories_index'),
    path('categories/<int:pk>/', views.categories_detail, name='categories_detail'),
    path('categories/new/', views.categories_new, name='categories_new'),
    path('categories/edit/<int:pk>/', views.categories_edit, name='categories_edit'),
    path('categories/delete/<int:pk>/', views.categories_delete, name='categories_delete'),
]

templates/shared/_filter_modal.html
<div class="modal fade" id="moto-filter-modal" tabindex="-1" role="dialog" aria-labelledby="moto-filter-modal-title" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">進階搜尋</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% include 'shared/_form.html' with method='GET' form=form %}
      </div>
    </div>
  </div>
</div>

templates/shared/_form.html
{% load bootstrap4 %}

<form action="{{ action }}" method="{{ method | default:'POST' }}" class="form" enctype="multipart/form-data">
  {% if method != 'GET' %}
    {% csrf_token %}
  {% endif %}

  {% bootstrap_form form %}

  {% buttons %}
    <button type="submit" class="btn btn-info float-right">
      送出
    </button>
  {% endbuttons %}
</form>

templates/shared/_form_modal.html
<div class="modal fade" id="moto-form-modal" tabindex="-1" role="dialog" aria-labelledby="moto-form-modal-title" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">建立新增{{name}}</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              {% include 'shared/_form.html' with action=action method='POST' form=form %}
            </div>
          </div>
        </div>
      </div>
      

templates/shared/_meta_form_modal.html
<div class="modal fade" id="form-modal-{{id}}" tabindex="-1" role="dialog" aria-labelledby="moto-form-modal-title" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">{{operator}}{{name}}</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              {% include 'shared/_form.html' with action=action method='POST' form=form %}
            </div>
          </div>
        </div>
      </div>
      

templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'root' %}">Moto</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarContent" aria-controls="navbarContent"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarContent">
    <ul class="navbar-nav mr-auto">
        <ul class="navbar-nav ml-lg-3">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'repair:index' %}">維修單</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'repair:report' %}">報表</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-lg-3">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">機車</a>
            </li>
        </ul>
    </ul>
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'index' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="車牌快速搜尋" aria-label="Search" name="id">
      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">搜尋</button>
    </form>
    <ul class="navbar-nav ml-lg-3">
        {% if request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'repair:categories_index' %}">維修項目管理</a>
          </li>
        {% endif %}
    </ul>
    <ul class="navbar-nav ml-lg-3">
        {% if request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">後台管理</a>
          </li>
        {% endif %}
    </ul>
    <ul class="navbar-nav ml-lg-3">
        <li class="nav-item">
          {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'admin:logout' %}?next=/">登出 ({{ request.user.username }})</a>
          {% else %}
            <a class="nav-link" href="{% url 'admin:login'%}?next=/">登入</a>
          {% endif %}
        </li>
    </ul>
  </div>
</nav>

templates/shared/_table.html
<table class="table table-striped">
{% for object in objects%}
  {% if forloop.first %}
    <thead>
      <tr>
      {% for field, value in object.fields.items %}
        <th scope="col">{{field}}</th>
      {% endfor %}
      </tr>
    <tbody>
  {% endif %}
      <tr>
        {% for field, value in object.fields.items %}
          {% if forloop.first %}
            <th scope="row">{{value|default:""}}</th>
          {% else %}
            <td>
                {{value}}
            </td>
          {% endif %}
        {% endfor %}
      </tr>
{% endfor %}
</tbody>
</table>

templates/shared/delete_confirm.html
{% extends 'layout.html' %}

{% block body %}
  <div class="row">
    <div class="col-6 offset-3">
      <h1>{{ title }}</h1>
      <hr>
      {% include 'shared/_table.html' with objects=objects %}
      <hr>
      <div class="float-right">
      {% include 'shared/_form.html' with form=form %}
      </div>
      <button class="btn btn-secondary float-left mr-2" onclick="window.history.back();">上一頁</button>
    </div>
  </div>
{% endblock %}